TYPING:
mypy wallet.py
Success: no issues found in 1 source file


 TESTING SINGLE TEST FILE:
 pytest test_wallet.py
================================================= test session starts =================================================
platform win32 -- Python 3.7.6, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: C:\Users\nvanderheijden\OneDrive - Deloitte (O365D)\Documents\source\unit_testing_example\tests
plugins: cov-2.8.1
collected 5 items

test_wallet.py .....                                                                                             [100%]

================================================== 5 passed in 0.10s ==================================================

TEST COVERAGE/PROJECT
pytest --cov=src tests/
================================================= test session starts =================================================
platform win32 -- Python 3.7.6, pytest-5.3.4, py-1.8.1, pluggy-0.13.1
rootdir: C:\Users\nvanderheijden\OneDrive - Deloitte (O365D)\Documents\source\unit_testing_example
plugins: cov-2.8.1
collected 5 items

tests\test_wallet.py .....                                                                                       [100%]

----------- coverage: platform win32, python 3.7.6-final-0 -----------
Name            Stmts   Miss  Cover
-----------------------------------
src\wallet.py      11      0   100%


================================================== 5 passed in 0.14s ==================================================

